### ISSUE TITLE
Add to bower

### ISSUE THREAD

**Issue by Monomachus** [RitsC/PrintArea#14]
Hello could you please add it to bower (http://bower.io/) components, so we could install and update it easily ?
As we already do it with lots of jquery plugins.

Thank you,
Timur

**Comment by maurotrigo** [comment]
Late, but registered: print-area

**Comment by RitsC** [comment]
I am not familiar with bower (i need to get there), in addition to my lack of time to support this simple plugin, which is why i have not addressed this issue.  However, dsbaars has contributed changes for support in bower, and some other changes.

Can you confirm that this solves this issue so that I can close it?

**Comment by maurotrigo** [comment]
Yeah, I think it does. I registered under your name and all, didn't take much time :)
I'm using it in one of my projects, it works perfectly.

Check it out: http://bower.io/search/?q=print-area

**Comment by RitsC** [comment]
Thank you! Glad it is working :)
