### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by syntk** [RitsC/PrintArea#15]
In Internet Explorer it prints the whole page not only the element. Tested in IE11 but it seems to happens in earlier versions too.
Using jQuery 1.10.2.

Thanks!

**Comment by RitsC** [comment]
I have tested using IE11 and IE10, jquery [1.9.0, 1.10.1, 1.11.0, 2.1.0] and cannot reproduce.  Can you provide more detail to help pinpoint the issue?

**Comment by syntk** [comment]
Only happens in iframe mode. Everything fine in popup mode.
Create a jQuery UI dialog, create a div inside and try to print that element. Let me know if you managed to reproduce the issue otherwise I will try to pack some files for you.

**Comment by RitsC** [comment]
I was not able to reproduce this issue. I created a simple dialog box using jquery-ui. Both when the dialog is open or closed, only the targeted content was printed.

**Comment by KEggleston** [comment]
Even this demo page doesn't work in IE11 in iframe mode:
http://www.jqueryscript.net/demo/Print-Specified-Area-Of-A-Page-PrintArea/demo/

**Comment by RitsC** [comment]
@KEggleston : If you download the demo from github, (NOT jqueryscript.net because they added a bunch of junk in the demo) and run it for yourself locally, it works fine.  There is something else going on with that page.  

As time permits, I'll look into what may be going on, because if you look at the iframe that is created by changing the iframe style to "...width:500px;height:600px;right:0px;top:0px;", the iframe contents look correct.  (and add "background: #eee;" helps).

In this case, I think it has something to do with the external link to css.

**Comment by RitsC** [comment]
I have added a new version that should fix these issues, let me know if not.
Thanks!
